from pathlib import Path
from IPython.display import HTML 

import pandas as pd
import webbrowser

#Function to color rows of document based on the status
def color_row(row):
    print(row)
    value = row.loc["Status"]
    if value == 'Open':
        color = 'aqua'
    elif value == 'Closed':
        color = 'green'
    else:
        color = 'black'
    return ['background-color: %s' % color for r in row]

#Directory of this file
this_dir = Path(__file__).resolve().parent

#Import excel file as pandas data file, keeping only specific cols
df = pd.read_excel(this_dir / "pir_report.xlsx", 
                   usecols=["Ticket","Category","Status","Part Number", "Facility", "Created", 
                            "Assigned To", "Reason", "Resolution"],
                             na_values="None DNE", keep_default_na=False)

#========== UPDATE FORMATING AND DROP DEAD ROWS =================
#number of junk rows at the end of the file to drop in processing
n = 4
#Clean last 4 lines which are generated by ERP
df.drop(df.tail(n).index, inplace=True)
dff = df.style.apply(color_row, axis=1)

###################################
head = ("""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<link href="pir.css" type="text/css" rel="stylesheet">
<title>Pandas Test</title>
</head>
<body>""")

foot = """
</body>
</html>
"""
####################################

#WRITE pir.html
with open("pir.html", "w", encoding="utf-8") as file:
    file.writelines(head + dff.to_html(na_rep=' ') + foot)
file.close()

#Open File
webbrowser.open_new_tab('pir.html')